### ISSUE TITLE
radix timers implementation

### ISSUE THREAD

**Issue by theAlexes** [romanf-dev/magnesium#1]
Hi, i remember you having a `rtimers` repo that had a separate MIT licensed implementation of Gray-coded radix timers. Is there any chance that can be reposted? This repo has a similar implementation but it isn't a separate library.

**Comment by romanf-dev** [comment]
Hi, sure. Please check the repo. I had decided to hide the repository since it lacks enough testing to be production-ready, i.e. overflows, etc (so be careful). After some research i figured out that usual binary encoding also performs well, so I use it in all my projects currently. Nevertheless, Gray-encoded version should be available in previous commits. Good luck!

**Comment by theAlexes** [comment]
Thank you!
